## 1. Numpy
### 1.1 Numpy 배열

In [3]:
import numpy as np

- numpy n-dim array(ndarray) vs list

In [2]:
l = [1, 2, 3, 4, 5]
l = l * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [3]:
n = np.array([1, 2, 3, 4, 5])
n = n * 2

array([ 2,  4,  6,  8, 10])

In [4]:
# 모든 수의 제곱수
[i * i  for i in l]

[1, 4, 9, 16, 25, 1, 4, 9, 16, 25]

In [5]:
np.square(n)        # parameter np.array로

array([  4,  16,  36,  64, 100])

- 1차원 배열(Vector)

In [6]:
a = np.array((1, 2, 3, 4, 5))       # tuple, list 사용 가능
type(a)

numpy.ndarray

In [7]:
a.dtype, a.shape, a.ndim, a.size        # int32 integer 32bit, (5,):tuple 만드는 법 

(dtype('int32'), (5,), 1, 5)

In [8]:
# 벡터화 연산
a * 2

array([ 2,  4,  6,  8, 10])

In [10]:
b = np.array([10, 20, 30, 40, 50])
c = 2 * a + b
c

array([12, 24, 36, 48, 60])

In [11]:
a == 2

array([False,  True, False, False, False])

In [12]:
b > 20

array([False, False,  True,  True,  True])

- 2차원 배열(Matrix)

In [15]:
c = np.array([[1, 2, 3], [4, 5, 6]])
c = np.arange(1, 7).reshape(2, 3)
c

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
c.dtype, c.shape, c.ndim, c.size        # shape:(2, 3) 2 rows 3 cols

(dtype('int32'), (2, 3), 2, 6)

- 3차원 배열(Tensor)

In [16]:
d = np.arange(1, 25).reshape(2, 3, 4)   # plane(2개), row(3개), col(4개)
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [17]:
d.dtype, d.shape, d.ndim, d.size

(dtype('int32'), (2, 3, 4), 3, 24)

- 배열의 인덱싱

In [18]:
a

array([1, 2, 3, 4, 5])

In [19]:
a[0], a[3], a[-1]

(1, 4, 5)

In [21]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
c[0][0], c[0, 0]

(1, 1)

In [25]:
c[1, 0], c[0, -1], c[-1, -1]

(4, 3, 6)

In [26]:
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [28]:
# 9, 20
d[0, -1, 0], d[-1, 1, -1]

(9, 20)

- 배열의 슬라이싱

In [29]:
# 리스트에서는 행, 열 슬라이싱이 동시에 안 됨.
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
l[:2]

[[1, 2, 3], [4, 5, 6]]

In [30]:
# 엉뚱한 결과가 나옴. 기대값 [[1, 2], [4, 5]]
l[:2][:2]

[[1, 2, 3], [4, 5, 6]]

In [31]:
l[1][:2]

[4, 5]

In [32]:
c = np.arange(1, 13).reshape(3, 4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
# 위 두행
c[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
# 오른쪽 두열
c[:, 2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [37]:
# 2, 3, 6, 7
c[:-1, 1:3]

array([[2, 3],
       [6, 7]])

In [42]:
# 1, 5, 3, 7
c[:-1, ::2]

array([[1, 3],
       [5, 7]])

- 연습문제2

In [47]:
m = np.arange(15).reshape(3, 5)
m[1, 2], m[-1, -1], m[1, 1:3], m[-2:, 2], m[:-1,-2:], m[-2:, 1::3]

(7,
 14,
 array([6, 7]),
 array([ 7, 12]),
 array([[3, 4],
        [8, 9]]),
 array([[ 6,  9],
        [11, 14]]))

In [48]:
# 1. 이 행렬에서 값 7을 인덱싱한다.
m[1, 2]

7

In [49]:
# 2. 이 행렬에서 값 14 을 인덱싱한다.
m[2, 4], m[-1, -1]

(14, 14)

In [50]:
# 3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
m[1, 1:3]

array([6, 7])

In [52]:
# 4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
m[-2:, 2]

array([ 7, 12])

In [53]:
# 5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
m[:-1,-2:]

array([[3, 4],
       [8, 9]])

In [55]:
# 맨 마지막 열이 y, 나머지는 X
X = m[:, :-1]       # X 대문자 2차원이상
y = m[:, -1]        # y 소문자 1차원

- 배열 인덱싱(Fancy indexing)

In [63]:
# idx 값이 True/False이면, True 값이 있는 곳의 원소만 통과(Filter)
a = np.array([1, 2, 3, 4, 5])
print(a)
idx = np.array([True, False, True, True, False])
print(a[idx])

[1 2 3 4 5]
[1 3 4]


In [64]:
# 홀수만 통과
a[a % 2 == 1]

array([1, 3, 5])

In [65]:
a[a > 3]

array([4, 5])

In [66]:
# idx 값이 정수(인덱스)면 해당 인덱스의 원소가 선택됨.
idx = np.array([1, 2, 4])
a[idx]

array([2, 3, 5])

- 연습문제3

In [4]:
x = np.arange(1, 21)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [73]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [74]:
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [76]:
x[(x % 3 == 0) & (x % 4 == 1)]      # elementwise / return array

array([9])

In [6]:
# 위의 결과는 ndarray. 원소의 값을 끄집어 내려면 다시 인덱싱해주서야 함.
x[(x % 3 == 0) & (x % 4 == 1)][0]   # 값으로 끄집어 내짐

9