### 1.3 배열의 연산(Operation)

In [1]:
import numpy as np

- 벡터화 연산

In [2]:
x = np.arange(1, 100001)
y = np.arange(100001, 200001)

In [8]:
%%time
z = np.empty_like(x)        # jupiter notebook 명령어 / %%time : 한셀 단위 / %time 한줄 단위 시간 체크
for i in range(100000):
    z[i] = x[i] + y[i]

CPU times: total: 46.9 ms
Wall time: 48 ms


In [9]:
%time z = x + y

CPU times: total: 0 ns
Wall time: 0 ns


In [13]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [11]:
a >= b

array([False,  True,  True,  True])

In [14]:
np.exp(a)           # a = 1, 2.718... 

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [15]:
10 ** a

array([   10,   100,  1000, 10000], dtype=int32)

In [17]:
5 * a

array([ 5, 10, 15, 20])

In [18]:
5 + a

array([6, 7, 8, 9])

- 차원 축소 연산

In [27]:
x = np.arange(1, 5, dtype='float64')
np.sum(x)

10.0

In [21]:
x.sum()

10

In [22]:
x.min(), x.max(), x.mean()      # 최소, 최대, 평균

(1, 4, 2.5)

In [23]:
# 대표값: 평균, 중앙값
np.mean(x), np.median(x)

(2.5, 2.5)

In [25]:
# 통계 : 분산, 표준편차
np.var(x), np.std(x)

(1.25, 1.118033988749895)

In [28]:
# 최소값, 최대값의 인덱스 (왼쪽에서 첫번째 값의 index)
y = np.array([1, 2, 3, 1, 3])
y.argmin(), y.argmax()

(0, 2)

- all / any
    - all : 모든게 True -> True / any : 하나라도 True -> True

In [30]:
np.all(np.array([True, True, False])), np.any(np.array([True, True, False]))

(False, True)

In [31]:
np.all(a == a)

True

- 2차원 이상의 연산

In [32]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
# 모든 원소의 합과 평균
np.sum(a), np.mean(a)

(21, 3.5)

In [35]:
'''
# 1 2 3
# 4 5 6
(0, 0) (0, 1) (0, 2)
(1, 0) (1, 1) (1, 2)
axis = 0, 각 좌표(row, col)에서 row를 변경시켜가면서 엑세스 / 변화시키는 값이 row
'''
np.sum(a, axis=0), np.mean(a, axis=0)

(array([5, 7, 9]), array([2.5, 3.5, 4.5]))

In [37]:
'''
# 1 2 3
# 4 5 6
(0, 0) (0, 1) (0, 2)
(1, 0) (1, 1) (1, 2)
axis = 1, 각 좌표(row, col)에서 col를 변경시켜가면서 엑세스
'''
np.sum(a, axis=1), np.mean(a, axis=1)

(array([ 6, 15]), array([2., 5.]))

In [41]:
b = np.arange(1, 13).reshape(2, 2, 3)
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [42]:
np.sum(b, axis=0)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [40]:
np.sum(b, axis=1)

array([[ 5,  7,  9],
       [17, 19, 21]])

In [43]:
np.sum(b, axis=2)

array([[ 6, 15],
       [24, 33]])

- 연습문제 3.3.1

In [46]:
np.random.seed = 2023
x = np.round(np.random.random(30).reshape(5, 6) * 10, 4)
x

array([[9.898 , 5.3268, 4.414 , 3.8462, 3.6367, 4.5315],
       [2.9726, 2.3265, 5.6985, 8.6266, 4.1354, 5.8614],
       [5.2915, 0.7854, 4.7653, 7.6273, 4.6763, 0.6135],
       [9.9076, 6.4894, 1.8738, 2.0368, 3.4   , 8.3772],
       [0.7995, 1.4173, 8.9338, 7.2877, 5.8566, 1.5045]])

In [49]:
np.max(x), np.sum(x, axis=1), np.max(x, axis=1), np.mean(x, axis=0), np.min(x, axis=0)

(9.9076,
 array([31.6532, 29.621 , 23.7593, 32.0848, 25.7994]),
 array([9.898 , 8.6266, 7.6273, 9.9076, 8.9338]),
 array([5.77384, 3.26908, 5.13708, 5.88492, 4.341  , 4.17762]),
 array([0.7995, 0.7854, 1.8738, 2.0368, 3.4   , 0.6135]))

- 정렬(sort)

In [50]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [51]:
np.sort(a)          # default axis=1

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [54]:
np.sort(a, axis=1)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [58]:
# 내림차순 정렬, axis=1일 경우
np.sort(a, axis=1)[:, ::-1]

array([[ 7,  5,  4,  3],
       [12, 11,  9,  1],
       [15, 14,  2,  1]])

In [59]:
np.sort(a, axis=0)[::-1,:]

array([[ 4, 15, 11, 14],
       [ 2, 12,  5,  9],
       [ 1,  3,  1,  7]])

In [60]:
# sort()는 자기 파괴적(in-place) method / in_place=True <- 자기값을 바꿈.
a.sort(axis=1)

In [61]:
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [69]:
a = np.array([4, 2, 1, 3])
np.argsort(a)           # 원래 자리의 인덱스

array([2, 1, 3, 0], dtype=int64)

- 연습 문제 3.3.2

In [72]:
ab = np.array([[  1,    2,    3,    4],
                [ 46,   99,  100,   71],
                [ 81,   59,   90,  100]])
ab

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [85]:
abc = ab.argsort(axis=1)
abc

array([[0, 1, 2, 3],
       [0, 3, 1, 2],
       [1, 0, 2, 3]], dtype=int64)

In [106]:
abcdef = ab[:, abc[1]]
abcdef

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])