### 1.5 난수 발생과 카운팅

In [1]:
import numpy as np

- 시드설정

In [2]:
np.random.seed(2003)
np.random.random(5)

array([0.49229035, 0.44559396, 0.40512847, 0.34639418, 0.84708402])

- 데이터의 순서 바꾸기

In [6]:
x = np.arange(10)
np.random.shuffle(x)        # x 데이터의 순서를 바꿈.
x

array([4, 6, 0, 5, 8, 2, 1, 3, 7, 9])

- 데이터의 샘플링

In [9]:
np.random.choice(5, 5, replace=False)       # 사이즈, 비복원 추출

array([2, 3, 4, 1, 0])

In [10]:
np.random.choice(5, 5, replace=True)        # 복원 추출

array([0, 0, 3, 0, 1])

In [10]:
x = np.random.randint(1, 100, 10)       # 1 <= x < 100
x

array([78, 92, 88, 46, 35, 35, 12,  2, 32, 70])

In [13]:
np.random.choice(x, 5, replace=False)

array([13, 10, 58, 44, 43])

- 난수 생성

In [14]:
# random(N) - Uniform 분포, 0 ~ 1 사이의 값 N개
np.random.random(10)

array([0.32993334, 0.18074191, 0.52992121, 0.66726225, 0.40868942,
       0.87711212, 0.10454456, 0.86512254, 0.39394613, 0.71887347])

In [15]:
# randint(low, high, N)  - [low, high) 범위의 정수 N개
np.random.randint(1, 7, 10)

array([1, 3, 4, 3, 1, 2, 3, 2, 1, 6])

In [16]:
# normal(평균, 표준편차, N) - 정규분포 N개
np.random.normal(170, 10, 10)

array([182.38581301, 188.03943476, 160.01231704, 177.69321649,
       180.11347854, 158.00033369, 180.35907631, 176.77838754,
       152.50912271, 169.57984953])

In [14]:
np.random.randn(12)

array([-0.84068261, -0.1655094 , -2.06841038,  0.45273874,  0.05113163,
       -0.23806075, -0.20800898,  0.40130411,  0.18316906,  1.23583026,
       -0.29180011,  0.02999245])

In [17]:
# randn - 표준정규분포 N(0, 1) N개
np.random.randn(10)

array([-0.07567456, -0.28446081, -0.30140776, -0.77294574,  0.6114751 ,
       -2.33829927,  1.12014223,  2.20318584,  0.88396431,  1.29856641])

In [18]:
np.random.binomial(1, 0.5, 20).reshape(4, 5)

array([[0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 1],
       [1, 0, 1, 0, 1]])

In [18]:
# binomial(시도횟수, 평균, N) - 이항분포 N개  / 동전 앞편 뒷면
np.random.binomial(10, 0.5, 20).reshape(4, 5)

array([[3, 6, 7, 6, 7],
       [6, 5, 6, 6, 5],
       [5, 5, 6, 7, 5],
       [6, 5, 6, 6, 3]])

In [19]:
# 가설검정 : t-검정 (1-sample T/원집단과 Sample, 2-sample T(남자 여자 비교), paired T(약물비교/원집단/비교집단))
# Student t(자유도, N)
np.random.standard_t(2, 10)

array([-2.08790809e+01,  1.28145335e+00, -1.58269250e+00,  2.51379990e-01,
        2.21224991e+00, -4.52625665e-01, -4.73320148e-01, -3.20182906e+00,
        1.10179355e-02,  3.37607597e+00])

- 연습문제 3.5.1
- 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성한다.

In [21]:
np.random.randint(0, 2, 10)

array([1, 0, 1, 1, 1, 1, 0, 0, 0, 1])

In [22]:
# 1. 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성한다.
np.random.binomial(1, 0.5, 10)

array([0, 1, 1, 0, 1, 1, 1, 0, 1, 1])

- 주사위를 100번 던져서 나오는 숫자의 평균을 구하라.

In [22]:
np.mean(np.random.randint(1, 7, 100))

3.53

- 연습문제 3.5.2
 - 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를
 - 따른다고 하자. 250일 동안의 주가를 무작위로 생성하라

In [28]:
# 5개만 먼저 테스트
rate = np.random.normal(0, 0.01, 5)
rate

array([-0.003936  , -0.0077979 ,  0.00341326, -0.00596979,  0.02962755])

In [30]:
price = 10000
for i in range(5):
    price = price * (1 + rate[i])       # price * (1 + r)
    price = int(round(price, 0))        # 가격의 단위는 원(소숫점 아래 자리는 버림)
    print(round(price, 2), end=' ')

9961 9883 9917 9858 10150 

In [34]:
# 250개의 수익률 생성
np.random.seed(2023)
rate = np.random.normal(0, 0.01, 250)
rate[:5]

array([ 0.00711674, -0.00324485, -0.01001871,  0.00236251, -0.0010216 ])

In [35]:
# 1. 리스트로 해결
price = 10000
price_list = []
for i in range(250):
    price = price * (1 + rate[i])
    price = int(round(price, 0))
    price_list.append(price)

price_list[-10:]        # 어레이로 만들고 싶으면    np.array(price_list])

[10814, 10893, 10674, 10645, 10588, 10724, 10739, 10686, 10691, 10497]

In [36]:
# 2. 어레이로 해결
price = 10000
price_array = np.empty(250, dtype=int)
for i in range(250):
    price = price * (1 + rate[i])
    price = int(round(price, 0))
    price_array[i] = price

price_array[-10:]

array([10814, 10893, 10674, 10645, 10588, 10724, 10739, 10686, 10691,
       10497])

- 데이터 카운팅

In [29]:
np.random.seed(2023)
dices = np.random.randint(1, 7, 100)
np.unique(dices, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([16, 18, 13, 15, 19, 19], dtype=int64))

In [30]:
indices, count = np.unique(dices, return_counts=True)
indices * count

array([ 16,  36,  39,  60,  95, 114], dtype=int64)

In [40]:
np.random.seed(2023)
dices = np.random.randint(1, 7, 100)

In [41]:
# 고유한 값
np.unique(dices)

array([1, 2, 3, 4, 5, 6])

In [42]:
# 고유한 값과 돗수
np.unique(dices, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([16, 18, 13, 15, 19, 19], dtype=int64))

In [43]:
indices, count = np.unique(dices, return_counts=True)
indices * count

array([ 16,  36,  39,  60,  95, 114], dtype=int64)

In [44]:
# 가중 평균
np.sum(indices * count) / np.sum(count)

3.6

In [45]:
np.mean(dices)      # 평균 계산시 가중 평균 값으로 계산

3.6

In [46]:
a = np.array(['x', 'y', 'x', 'y', 'z', 'y'])
np.unique(a, return_counts=True)

(array(['x', 'y', 'z'], dtype='<U1'), array([2, 3, 1], dtype=int64))